Herobrine:
  # The higher the chance, the more rare actions are.
  actionChance: 100000
  # Send messages or be quiet.
  sendMessages: true
  # Modify the world (bury players, add torches, etc.)
  modifyWorld: true
  # Place fire where he walks.
  fireTrails: false
  # Don't attack creative players.
  ignoreCreativePlayers: true
  # Can he smash nearby torches?
  smashTorches: false
  # Can they summon him by altar?
  allowAltar: true
  # What he drops on death and the amount.
  deathDrop: 264,1
  # Possible messages he can send.
  messages:
    - I am your God!
    - I will always prevail!
    - Never doubt my power!
    - Where is your God now?
    - Bless this!
  # Messages that can appear on signs (keep them short!)
  signMessages:
    - Remember me?
    - I'm watching.
    - Stop
    - I'm alive.
    - Don't forget.
    - I'm here.
    - Always watching.
    - Never forget.
  # What worlds he can do things in.
  allowedWorlds:
    - world
    - world_nether
    - world_the_end
  # Don't touch this, this is for me to use.
  configBuild: 4.0
  # Allow me to collect server statistics (see BukktDev page).
  collectStats: true