Herobrine:
  # The higher the chance, the more rare actions are.
  actionChance: 100000
  # Send messages or be quiet.
  sendMessages: true
  # Modify the world (bury players, add torches, etc.)
  modifyWorld: true
  # Can he steal from chests?
  stealFromChests: true
  # What is his name? (This will affect his skin!)
  entityName: Herobrine
  # Don't attack creative players.
  ignoreCreativePlayers: true
  # Can they summon him by altar?
  allowAltar: true
  # Log event messages?
  logEvents: true
  # What should he be holding?
  itemInHand: 259
  # Should he be more often at night and when players are online?
  moreOftenAtNight: true
  # How long will he appear for (this is in seconds)?
  appearanceTime: 3
  # There are blocks he can modify, you should not use man-made ones!
  allowedBlocks:
    - 1
    - 2
    - 3
    - 12
  # Possible messages he can send.
  messages:
    - I am your God!
    - I will always prevail!
    - Never doubt my power!
    - Where is your God now?
    - Bless this!
  # Messages that can appear on signs (keep them short!)
  signMessages:
    - I'm watching.
    - Stop.
    - I'm here.
    - Never forget.
    - The eyes.
    - Bright white eyes.
    - Blinding eyes.
  # What he can write in books.
  bookMessages:
    - Hello.
    - I'm still here.
    - I'm getting closer.
  # What worlds he can do things in.
  allowedWorlds:
    - world
    - world_nether
    - world_the_end
  # Don't touch this, this is for me to use.
  configBuild: 4.6
  # Allow me to collect server statistics.
  collectStats: true